[package]
name = "anime_wallpaper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.7"
rand = "0.8"
dirs = "6.0.0"
urlencoding = "2.1.3"
